### ISSUE TITLE
Rosco package updates

### ISSUE THREAD

**Issue by marchdf** [Exawind/exawind-manager#12]
Creating this so we don't lose track. ROSCO version 2.9 reorganized a bunch of folder locations. This breaks the rosco package we have. The `root_cmakelists_dir = 'ROSCO'` is now `rosco/controller` for 2.9.

**Comment by psakievich** [comment]
@ndevelder

**Comment by marchdf** [comment]
fixed in https://github.com/spack/spack/pull/43822
